import type { DbClient } from "./prisma";

export const defaultMotivationQuotes = [
  { source: "Friedrich Nietzsche", text: "He who has a why can bear almost any how." },
  { source: "Viktor Frankl", text: "What is to give light must endure burning." },
  { source: "Viktor Frankl", text: "When we cannot change a situation, we are challenged to change ourselves." },
  { source: "Bob Hooey", text: "If you are not taking care of your customer, your competitor will." },
  { source: "Tony Hsieh", text: "Chase the vision, not the money; the money will end up following you." },
  { source: "Jim Cathcart", text: "Become the person who would attract the results you seek." },
  { source: "Michael Jordan", text: "You must expect great things of yourself before you can do them." },
  { source: "Mark Roberge", text: "It is about listening, diagnosing and prescribing." },
  { source: "Bruce Lee", text: "I fear the man who has practiced one kick 10,000 times." },
  { source: "George Addair", text: "Everything you have ever wanted is on the other side of fear." },
  { source: "Jeffrey Gitomer", text: "Great salespeople are relationship builders who provide value." },
  { source: "Frank Bettger", text: "If you do not believe in what you are selling, neither will your prospect." },
  { source: "Steve Jobs", text: "If you really care about the work, the vision pulls you." },
  { source: "Ralph Marston", text: "Excellence is not a skill. It is an attitude." },
  { source: "Shiv Khera", text: "90 percent of selling is conviction and 10 percent is persuasion." },
  { source: "Patricia Fripp", text: "You do not compete on price. You compete on relationships." },
  { source: "r/sales", text: "A confused mind always says no." },
  { source: "r/sales", text: "Every sale follows a process, either yours or the customer's." },
  { source: "r/sales", text: "Price, quality, and service. Pick any two." },
  { source: "Seth Godin", text: "Do not find customers for your products; find products for your customers." },
  { source: "Katherine Barchetti", text: "Make a customer, not a sale." },
  { source: "Bill Gates", text: "Your most unhappy customers are your greatest source of learning." },
  { source: "William C. Stone", text: "Sales are contingent upon the attitude of the salesman." },
  { source: "Jim Rohn", text: "Either you run the day, or the day runs you." },
  { source: "Will Rogers", text: "Even if you are on the right track, you will get run over if you just sit there." },
  { source: "Wayne Gretzky", text: "You miss 100 percent of the shots you do not take." },
  { source: "Dan Pena", text: "You're 2000 cold calls away from being a millionaire." },
  { source: "Tim Ferriss", text: "Focus on being productive instead of being busy." },
  { source: "Jocko Willink", text: "Do not count on motivation. Count on discipline." },
  { source: "Elon Musk", text: "You should take the approach that you are wrong. Your goal is to be less wrong." },
  { source: "Elon Musk", text: "You get paid in direct proportion to the difficulty of problems you solve." },
  { source: "Elon Musk", text: "No, I don't ever give up. I'd have to be dead or completely incapacitated." },
  { source: "Elon Musk", text: "Life needs to be more than just solving problems every day." },
  { source: "Elon Musk", text: "When something is important enough, you do it even if the odds are not in your favor." },
  { source: "Elon Musk", text: "If you need motivation, don't do it." },
  { source: "Elon Musk", text: "Some people don't like change, but you need to embrace change if the alternative is disaster." },
  { source: "Elon Musk", text: "Persistence is very important. You should not give up unless you are forced to give up." },
  { source: "Elon Musk", text: "It is OK to have your eggs in one basket as long as you control what happens to that basket." },
  { source: "Elon Musk", text: "Really pay attention to negative feedback and solicit it, particularly from friends." },
  { source: "Elon Musk", text: "No task is too menial." },
  { source: "Elon Musk", text: "Spend your time solving engineering and manufacturing problems." },
  { source: "Elon Musk", text: "Process becomes a substitute for thinking." },
  { source: "Elon Musk", text: "It is a mistake to hire huge numbers of people to get a complicated job done." },
  { source: "Elon Musk", text: "It is very important to like the people you work with." },
  { source: "Mike Puglia", text: "Establishing trust is better than any sales technique." },
  { source: "Mark Twain", text: "The secret of getting ahead is getting started." },
  { source: "r/sales", text: "A goal without a plan is just a wish." },
  { source: "r/sales", text: "When you lose, say little. When you win, say less." },
  { source: "r/sales", text: "If you say you are going to do something, do it." },
  { source: "r/sales", text: "The more I prospect, the luckier I get." },
  { source: "r/sales", text: "The sale begins when the customer says no." },
  { source: "John Wooden", text: "Do not let what you cannot do interfere with what you can do." },
  { source: "Nelson Mandela", text: "I never lose. I either win or learn." },
  { source: "Thomas Edison", text: "The most certain way to succeed is to try just one more time." },
  { source: "Seth Godin", text: "If it scares you, it might be a good thing to try." },
  { source: "Henry Ford", text: "You cannot build a reputation on what you are going to do." },
  { source: "Bob Burg", text: "Sometimes the most influential thing we can do is listen." },
  { source: "r/sales", text: "Nothing happens until somebody sells something." },
  { source: "r/sales", text: "When there is a lack of value, everything comes down to price." },
  { source: "r/sales", text: "You have two ears and one mouth for a reason." },
  { source: "r/sales", text: "Win fast, win slow. Lose fast." },
  { source: "Richard Thaler", text: "If you want somebody to do something, make it easy." },
  { source: "r/sales", text: "Logic unlocks the mind; emotion unlocks the pocketbook." },
  { source: "r/sales", text: "Just because they said no does not mean they will not sign." },
  { source: "r/sales", text: "Learn to take yes for an answer." },
  { source: "r/sales", text: "If a customer did not say it, it is not true." },
  { source: "Ann Landers", text: "Opportunities are usually disguised as hard work." },
  { source: "Zig Ziglar", text: "If you aim at nothing, you will hit it every time." },
  { source: "Henry Ford", text: "Whether you think you can or cannot, you are right." },
  { source: "Jill Konrath", text: "Sales is an outcome, not a goal." },
  { source: "Brian Tracy", text: "Approach each customer with the idea of helping them solve a problem." },
  { source: "Jill Rowley", text: "Always Be Closing has become Always Be Connecting." },
  { source: "Babe Ruth", text: "You just cannot beat the person who never gives up." },
  { source: "Jim Rohn", text: "Practice makes skill. Skill makes fortune." },
  { source: "Brian Tracy", text: "Sales success is 80 percent attitude and 20 percent aptitude." },
  { source: "Thomas Freese", text: "The questions you ask are more important than the things you say." },
  { source: "George Bernard Shaw", text: "Life is not about finding yourself. Life is about creating yourself." },
  { source: "Suzy Kassem", text: "Doubt kills more dreams than failure ever will." },
  { source: "Walt Whitman", text: "Keep your face always toward the sunshine, and shadows will fall behind you." },
  { source: "Marcus Aurelius", text: "The happiness of your life depends on the quality of your thoughts." },
  { source: "Aristotle", text: "It is during our darkest moments that we must focus to see the light." },
  { source: "Michael Altshuler", text: "The bad news is time flies. The good news is you are the pilot." },
  { source: "Brian Tracy", text: "Move out of your comfort zone." },
  { source: "Helen Keller", text: "Never bend your head. Always hold it high." },
  { source: "Walt Disney", text: "The best way to get started is to quit talking and begin doing." },
  { source: "Brian Tracy", text: "Leaders set high standards." },
  { source: "Brian Tracy", text: "There are no limits except the limits you place on your own thinking." },
  { source: "Brian Tracy", text: "Your life only gets better when you get better." },
];

export async function ensureDefaultMotivationQuotes(workspaceId: string, db: DbClient) {
  const existingQuotes = await db.motivationQuote.findMany({
    where: { workspaceId, text: { in: defaultMotivationQuotes.map((quote) => quote.text) } },
    select: { text: true },
  });
  const existingTexts = new Set(existingQuotes.map((quote) => quote.text));
  const missingQuotes = defaultMotivationQuotes.filter((quote) => !existingTexts.has(quote.text));
  if (!missingQuotes.length) return;

  await db.motivationQuote.createMany({
    data: missingQuotes.map((quote) => ({ workspaceId, ...quote })),
    skipDuplicates: true,
  });
}

export async function getMotivationQuotes(workspaceId: string, db: DbClient) {
  await ensureDefaultMotivationQuotes(workspaceId, db);

  return db.motivationQuote.findMany({
    where: { workspaceId, isActive: true },
    orderBy: [{ upvotes: "desc" }, { createdAt: "asc" }],
    take: 200,
  });
}
